Repository ormcamp-fe-3rd/FlightLog, pull requests merged in 2025-02, with the labels that each got.

#38 [map] 재생바 타임라인 및 zoom 기능 추가
  src/app/map/page.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/StatusPanel.tsx
  src/components/map/Timeline.tsx
  src/constants.ts
  src/hooks/useDronePosition.ts
  src/hooks/useOperationData.ts
  src/hooks/usePlayback.ts
  src/types/types.ts
  src/utils/getTimelineStyles.ts
  src/utils/mapCalculator.ts
  src/utils/timelineCalculator.ts
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현

#42 [common] 사용자가 선택한 로봇 데이터만 받아오도록 개선
  src/app/(data)/map/page.tsx
  src/components/common/Sidebar.tsx
  src/lib/dbService.ts
  src/store/useData.ts
Labels: 💡 리뷰어 PR 요청, 🔨 최적화

#43 [map] 드론 움직임 재생 관련 사용성 개선
  src/app/map/page.tsx
  src/hooks/usePlayback.ts
  src/utils/timelineCalculator.ts
Labels: ⚙️ 기능 구현

#44 [log] 사이드바 라벨링, 로딩 중 ui, 유저의 로그인 상태 검증
  src/app/(data)/layout.tsx
  src/components/common/AppProvider.tsx
  src/components/common/LoginButton.tsx
  src/components/common/Sidebar.tsx
  src/components/home/LoginContent.tsx
  src/components/home/RegisterContent.tsx
  src/components/home/ServiceStart.tsx
  src/components/home/SocialLoginButton.tsx
  src/components/log/charts/MultipleAxesCharts.tsx
  src/lib/dbService.ts
  src/store/useData.ts
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현, 🔧 기능 추가

#47 [log]차트 데이터 그룹변경 및 차트 구분화
  package-lock.json
  public/images/map/marker-icon.png
  src/app/(data)/log/page.tsx
  src/components/log/charts/AttitudeCharts.tsx
  src/components/log/charts/StatusCharts.tsx
  src/hooks/useAttitudeChartsData .tsx
  src/hooks/useChartsData.tsx
  src/hooks/useStatusChartsData.tsx
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현

#46 [map] map 페이지 기능 추가/보완 (드론 날개, 드롭박스 등)
  src/app/map/page.tsx
  src/components/map/AttitudePanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/SelectFlightLog.tsx
  src/types/types.ts
  src/utils/isFlightActive.ts
  src/utils/mapCalculator.ts
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현, 🔩 배포 준비

#53 [사이드바, map] 버그 수정 1차
  src/app/(data)/map/page.tsx
  src/components/common/Sidebar.tsx
  src/components/map/AttitudePanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/StatusPanel.tsx
  src/constants.ts
  src/store/useData.ts
  src/utils/calculateTotalTimeGap.ts
Labels: 🪲 버그

#54 [map] 빌드 오류 수정(leaflet)
  src/app/(data)/map/page.tsx
  src/utils/mapCalculator.ts
Labels: 🪲 버그, 🔩 배포 준비

#58 [map] 선택 비행 자동 변경 기능 및 추적 모드 추가
  src/app/(data)/map/page.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/Timeline.tsx
  src/components/map/TrackingToggle.tsx
  src/hooks/usePlayback.ts
Labels: 🔧 기능 추가

#64 [log]추가 issue 해결 및 로그페이지 레이아웃 수정
  src/app/(data)/layout.tsx
  src/app/(data)/log/page.tsx
  src/app/(data)/map/page.tsx
  src/components/common/Header.tsx
  src/components/home/Cards.tsx
  src/components/log/charts/AttitudeCharts.tsx
  src/components/log/charts/StatusCharts.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/Timeline.tsx
  src/components/map/TrackingToggle.tsx
  src/constants.ts
  src/hooks/useAttitudeChartsData .tsx
  src/hooks/useChartsData.tsx
  src/hooks/usePlayback.ts
  src/hooks/useResizePanelControl.ts
  src/hooks/useStatusChartsData.tsx
  src/store/useSidebar.ts
Labels: ⚙️ 기능 구현, 🎨 html css 수정
