Repository ormcamp-fe-3rd/FlightLog, pull requests merged in 2025-01, with the labels that each got.

#12 [공통] 푸터 레이아웃
  src/app/layout.tsx
  src/components/common/Footer.tsx
Labels: 🎨 html css 수정

#11 [login] 로그인 페이지 레이아웃
  src/app/login/page.tsx
Labels: 🎨 html css 수정

#20 [map] map 페이지 반응형 처리 (사이드바 등)
  package-lock.json
  package.json
  public/images/common/icon-map.svg
  public/images/common/icon-pie-chart.svg
  public/images/map/icon-control-attitude.svg
  public/images/map/icon-control-info.svg
  public/images/map/icon-control-zoom.svg
  public/images/map/icon-menu.svg
  src/app/layout.tsx
  src/app/map/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Sidebar.tsx
  src/components/map/AttitudePanel.tsx
  src/components/map/ControlPanel.tsx
  src/components/map/StatusPanel.tsx
  src/store/useSidebar.ts
  tailwind.config.ts
Labels: 💬 팀원 PR 필요, ⚙️ 기능 구현, 🎨 html css 수정

#17 [design] home 화면 기본 레이아웃 세팅
  public/images/common/.gitkeep
  public/images/home/Agri-drone.jpg
  public/images/home/construction-drone.jpg
  public/images/home/facebook-logo.svg
  public/images/home/flight-log-main-image.jpg
  public/images/home/github-logo.svg
  public/images/home/insta-logo.svg
  public/images/home/x-logo.svg
  public/images/log/.gitkeep
  public/images/login/.gitkeep
  public/images/map/.gitkeep
  src/app/page.tsx
  src/assets/images/login/.gitkeep
  src/assets/images/map/.gitkeep
  src/components/home/Cards.tsx
  src/components/home/DataService.tsx
  src/components/home/ImageGallery.tsx
  src/components/home/ServiceStart.tsx
  src/components/home/ServiceTitle.tsx
  tailwind.config.ts
Labels: 🎨 html css 수정

#22 [Login] 모달 작업 전 pull, 셋팅
  package-lock.json
  package.json
  public/images/common/.gitkeep
  public/images/common/icon-map.svg
  public/images/common/icon-pie-chart.svg
  public/images/home/.gitkeep
  public/images/home/Agri-drone.jpg
  public/images/home/construction-drone.jpg
  public/images/home/facebook-logo.svg
  public/images/home/flight-log-main-image.jpg
  public/images/home/github-logo.svg
  public/images/home/insta-logo.svg
  public/images/home/x-logo.svg
  public/images/log/.gitkeep
  public/images/login/.gitkeep
  public/images/map/.gitkeep
  public/images/map/icon-Accuracy.svg
  public/images/map/icon-Altitude.svg
  public/images/map/icon-Flight.svg
  public/images/map/icon-GPS.svg
  public/images/map/icon-control-attitude.svg
  public/images/map/icon-control-info.svg
  public/images/map/icon-control-zoom.svg
  public/images/map/icon-menu.svg
  public/images/map/marker-icon.png
  src/app/layout.tsx
  src/app/map/page.tsx
  src/app/page.tsx
  src/assets/images/login/.gitkeep
  src/assets/images/map/.gitkeep
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Sidebar.tsx
  src/components/home/Cards.tsx
  src/components/home/DataService.tsx
  src/components/home/ImageGallery.tsx
  src/components/home/LoginModal.tsx
  src/components/home/ServiceStart.tsx
  src/components/home/ServiceTitle.tsx
  src/components/map/AttitudePanel.tsx
  src/components/map/ControlPanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/StatusPanel.tsx
  src/store/useSidebar.ts
  tailwind.config.ts
Labels: 🎨 html css 수정

#26 [map] db 데이터 연결 및 사이드바, 지도 적용
  global.d.ts
  jest.config.js
  package-lock.json
  package.json
  src/app/api/[collection]/route.test.ts
  src/app/api/[collection]/route.ts
  src/components/common/Sidebar.tsx
  src/components/map/MapView.tsx
  src/lib/database.ts
  src/lib/dbService.ts
  src/lib/fetchClient.ts
  src/lib/validators.ts
  src/store/useData.ts
  src/types/api.d.ts
  src/utils/formatTimestamp.ts
  src/utils/getColorFromId.ts
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현

#23 [login] 로그인 모달 구현 및 회원가입 로직 추가
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/register/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/AuthProvider.tsx
  src/components/common/Header.tsx
  src/components/common/LoginButton.tsx
  src/components/home/AuthModal.tsx
  src/components/home/DataService.tsx
  src/components/home/LoginContent.tsx
  src/components/home/LoginModal.tsx
  src/components/home/RegisterContent.tsx
  src/components/home/SocialLoginButton.tsx
  src/hook/usePreventScroll.tsx
  src/store/useLoginModal.ts
  src/util/common/AuthLogin.ts
  src/util/common/RegsiterFormFormat.ts
  src/util/common/database.ts
Labels: 💡 리뷰어 PR 요청, ⚙️ 기능 구현

#30 [map] 지도에 마커 추가, 프로그래스바 연동
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/images/map/marker-icon.png
  src/app/map/page.tsx
  src/components/map/AttitudePanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/global.d.ts
  tsconfig.json
Labels: ⚙️ 기능 구현, 🔧 기능 추가

#31 [map] 사이드바 수정(피드백 반영), 선택 비행 별도 움직임 구현
  package-lock.json
  public/images/map/marker-icon.png
  src/app/map/page.tsx
  src/components/common/Sidebar.tsx
  src/components/map/ControlPanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/SelectFlightLog.tsx
  src/constants.ts
  src/hooks/useResizePanelControl.ts
  src/store/useData.ts
  src/utils/findOperationStartTime.ts
  src/utils/formatTimestamp.ts
Labels: ⚙️ 기능 구현

#32 [log] 그래프를 통한 드론 배터리 정보 시각화
  src/app/log/page.tsx
  src/components/log/charts/MultipleAxesCharts.tsx
Labels: 🚨 질문 도움 요청, 💡 리뷰어 PR 요청, ⚙️ 기능 구현

#36 [map] 재생바 시간별 Status Panel 정보 출력
  src/app/map/page.tsx
  src/components/map/ControlPanel.tsx
  src/components/map/FlightProgressBar.tsx
  src/components/map/MapView.tsx
  src/components/map/SelectFlightLog.tsx
  src/components/map/StatusPanel.tsx
  src/constants.ts
  src/hooks/useTelemetryData.ts
  src/utils/calculateCurrentTime.ts
  src/utils/formatTimestamp.ts
Labels: ⚙️ 기능 구현, 🎨 html css 수정

#34 [log] 차트에 데이터 랜더링시 각각 드론의 따라 분리 로직
  src/components/log/charts/SynchronisedCharts.tsx
  src/hooks/useChartsData.tsx
  src/hooks/useSynchronisedChartsData .tsx
  src/types/api.d.ts
Labels: 🚨 질문 도움 요청, 💡 리뷰어 PR 요청, ⚙️ 기능 구현
